### ISSUE TITLE
能否增加博客文章的显示宽度

### ISSUE THREAD

**Issue by pandaye** [hifun-team/hexo-theme-miracle#25]
source/css/_includes/post.styl 这里
```css
@media (min-width: 768px) {
  article[class='page'] {
    max-width: 650px;
  }
}
```
650 对于大多数 1920x1080 的屏幕，感觉有些狭窄，是否考虑增加一些宽度？

```css
@media (min-width: 1200px) {
  article[class='page'] {
    max-width: 1000px;
  }
}
```
